// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ChatRole string

const (
	ChatRoleUser      ChatRole = "user"
	ChatRoleAssistant ChatRole = "assistant"
)

func (e *ChatRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChatRole(s)
	case string:
		*e = ChatRole(s)
	default:
		return fmt.Errorf("unsupported scan type for ChatRole: %T", src)
	}
	return nil
}

type NullChatRole struct {
	ChatRole ChatRole
	Valid    bool // Valid is true if ChatRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChatRole) Scan(value interface{}) error {
	if value == nil {
		ns.ChatRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChatRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChatRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChatRole), nil
}

type OauthProvider string

const (
	OauthProviderGoogle OauthProvider = "google"
	OauthProviderGithub OauthProvider = "github"
)

func (e *OauthProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OauthProvider(s)
	case string:
		*e = OauthProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for OauthProvider: %T", src)
	}
	return nil
}

type NullOauthProvider struct {
	OauthProvider OauthProvider
	Valid         bool // Valid is true if OauthProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOauthProvider) Scan(value interface{}) error {
	if value == nil {
		ns.OauthProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OauthProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOauthProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OauthProvider), nil
}

type SourceStatus string

const (
	SourceStatusPending    SourceStatus = "pending"
	SourceStatusProcessing SourceStatus = "processing"
	SourceStatusIndexed    SourceStatus = "indexed"
	SourceStatusFailed     SourceStatus = "failed"
)

func (e *SourceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SourceStatus(s)
	case string:
		*e = SourceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SourceStatus: %T", src)
	}
	return nil
}

type NullSourceStatus struct {
	SourceStatus SourceStatus
	Valid        bool // Valid is true if SourceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSourceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SourceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SourceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSourceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SourceStatus), nil
}

type SourceType string

const (
	SourceTypeLink SourceType = "link"
	SourceTypePdf  SourceType = "pdf"
	SourceTypePpt  SourceType = "ppt"
	SourceTypeDoc  SourceType = "doc"
	SourceTypeNote SourceType = "note"
)

func (e *SourceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SourceType(s)
	case string:
		*e = SourceType(s)
	default:
		return fmt.Errorf("unsupported scan type for SourceType: %T", src)
	}
	return nil
}

type NullSourceType struct {
	SourceType SourceType
	Valid      bool // Valid is true if SourceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSourceType) Scan(value interface{}) error {
	if value == nil {
		ns.SourceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SourceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSourceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SourceType), nil
}

type ChatMessage struct {
	ID        pgtype.UUID
	SessionID pgtype.UUID
	Role      ChatRole
	Content   string
	CreatedAt pgtype.Timestamptz
}

type ChatSession struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Title     string
	CreatedAt pgtype.Timestamptz
}

type Collection struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

type OauthAccount struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	Provider       OauthProvider
	ProviderUserID string
	Email          pgtype.Text
	CreatedAt      pgtype.Timestamptz
}

type PasswordReset struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Token     string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type PasswordResetToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Session struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	ExpiresAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
	UserAgent  pgtype.Text
	IpAddress  pgtype.Text
	IsRevoked  bool
}

type Source struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	CollectionID pgtype.UUID
	Type         SourceType
	Status       SourceStatus
	Title        string
	OriginalUrl  pgtype.Text
	S3Bucket     pgtype.Text
	S3Key        pgtype.Text
	ContentHash  pgtype.Text
	CreatedAt    pgtype.Timestamptz
	ImageUrl     pgtype.Text
}

type SourceContent struct {
	ID          pgtype.UUID
	SourceID    pgtype.UUID
	ContentText string
	ContentHash string
	CreatedAt   pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Email        string
	Username     pgtype.Text
	ImageUrl     pgtype.Text
	PasswordHash string
	Verified     bool
	CreatedAt    pgtype.Timestamptz
}
