// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: source_content.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSourceContent = `-- name: CreateSourceContent :exec
INSERT INTO source_contents (source_id, content_text)
VALUES ($1, $2)
`

type CreateSourceContentParams struct {
	SourceID    pgtype.UUID
	ContentText string
}

func (q *Queries) CreateSourceContent(ctx context.Context, arg CreateSourceContentParams) error {
	_, err := q.db.Exec(ctx, createSourceContent, arg.SourceID, arg.ContentText)
	return err
}

const getSourceContentBySourceID = `-- name: GetSourceContentBySourceID :many
SELECT id, source_id, content_text, content_hash, created_at FROM source_contents WHERE source_id = $1
`

func (q *Queries) GetSourceContentBySourceID(ctx context.Context, sourceID pgtype.UUID) ([]SourceContent, error) {
	rows, err := q.db.Query(ctx, getSourceContentBySourceID, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SourceContent
	for rows.Next() {
		var i SourceContent
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.ContentText,
			&i.ContentHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
