// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sources.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateSourceStatus = `-- name: UpdateSourceStatus :exec
UPDATE sources 
SET status = $2
WHERE id = $1
`

type UpdateSourceStatusParams struct {
	ID     pgtype.UUID
	Status SourceStatus
}

func (q *Queries) UpdateSourceStatus(ctx context.Context, arg UpdateSourceStatusParams) error {
	_, err := q.db.Exec(ctx, updateSourceStatus, arg.ID, arg.Status)
	return err
}
